# --- Project Configuration ---
project:
  type: default
  output-dir: output

# --- Execution Settings ---
execute:
  freeze: auto
  message: true
  warning: true
  
# --- Bibliography & Citations ---
bibliography: references.bib
csl: journal-of-clinical-oncology.csl

# --- Format Configuration ---
format:
  # --- HTML Settings ---
  html:
    # --- Document Settings ---
    theme: cosmo
    code-fold: true
    toc: true
    toc-location: right
    embed-resources: true
    css: style.css
    code-links:
      - text: GitHub Repo
        icon: github
        href: https://github.com/EDukeChase/gi-cancer_project

# --- Document Language
lang: en