project:
  type: default

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    code-fold: show
    toc: true
    toc-location: right
    embed-resources: true
    css: style.css
    code-links:
      repo

lang: en